import React, { useState } from 'react';
import { Download, FileText, Calendar, Filter, ChevronDown, PieChart } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';

const yieldHistoryData = [
  { year: '2022', Tomato: 12, Cotton: 0, Groundnut: 4 },
  { year: '2023', Tomato: 15, Cotton: 8, Groundnut: 5 },
  { year: '2024', Tomato: 14, Cotton: 10, Groundnut: 6 },
  { year: '2025', Tomato: 18, Cotton: 12, Groundnut: 5 },
];

const ReportsHistoryTab = ({ activeFarm }) => {
  const [dateRange, setDateRange] = useState('Last 12 Months');

  const handleDownloadPDF = (row) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>${row.type} Report - ${row.crop}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; }
            h1 { color: #059669; border-bottom: 2px solid #059669; padding-bottom: 10px; }
            h2 { color: #1f2937; }
            .detail { margin-bottom: 12px; font-size: 16px; display: flex; }
            .detail strong { width: 150px; color: #4b5563; }
            .risk-Low { color: #16a34a; font-weight: bold; background: #dcfce7; padding: 2px 8px; border-radius: 4px; }
            .risk-Moderate { color: #ca8a04; font-weight: bold; background: #fef08a; padding: 2px 8px; border-radius: 4px; }
            .risk-High { color: #dc2626; font-weight: bold; background: #fee2e2; padding: 2px 8px; border-radius: 4px; }
            .footer { margin-top: 40px; font-size: 12px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>Smart Agriculture Management System (SAMS)</h1>
          <h2>Analysis Report: ${row.type}</h2>
          
          <div style="background: #f9fafb; padding: 20px; border-radius: 8px; border: 1px solid #e5e7eb; margin: 20px 0;">
            <div class="detail"><strong>Date:</strong> ${row.date}</div>
            <div class="detail"><strong>Crop Context:</strong> ${row.crop}</div>
            <div class="detail"><strong>Risk Level:</strong> <span class="risk-${row.risk}">${row.risk}</span></div>
          </div>
          
          <h3>Report Summary</h3>
          <p>This is an automated AI analysis report generated based on historical agricultural datasets, satellite imagery indices, and real-time environmental telemetry data for the selected region.</p>
          
          <h3>Key Recommendations for ${row.crop}</h3>
          <ul>
            <li>Monitor local weather conditions and adjust irrigation schedules accordingly.</li>
            <li>Implement preventative pest control measures appropriate for the ${row.risk} risk level.</li>
            <li>Refer to the SAMS dashboard for real-time market value estimations before harvesting.</li>
          </ul>
          
          <div class="footer">
            Generated by SAMS AI Engine &bull; Document ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-2 flex-wrap gap-4">
        <h3 className="text-xl font-bold">Reports & History</h3>
        <div className="flex gap-2">
          <button onClick={() => alert("Opening advanced filter options...")} className="btn-outline flex items-center gap-2 text-sm bg-white dark:bg-gray-800">
            <Filter className="w-4 h-4"/> Filter
          </button>
          <button onClick={() => window.print()} className="btn-primary flex items-center gap-2 text-sm">
            <Download className="w-4 h-4"/> Export PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="card p-6 border-l-4 border-agri-green">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 bg-green-100 rounded-lg text-green-600">
              <PieChart className="w-6 h-6"/>
            </div>
            <div>
              <h4 className="font-bold text-gray-700 dark:text-gray-300">Total Yield</h4>
              <p className="text-sm text-gray-500">All time production</p>
            </div>
          </div>
          <p className="text-3xl font-bold">145 <span className="text-lg font-normal text-gray-500">Tons</span></p>
        </div>

        <div className="card p-6 border-l-4 border-blue-500">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 bg-blue-100 rounded-lg text-blue-600">
              <Calendar className="w-6 h-6"/>
            </div>
            <div>
              <h4 className="font-bold text-gray-700 dark:text-gray-300">Active Seasons</h4>
              <p className="text-sm text-gray-500">Farming cycles</p>
            </div>
          </div>
          <p className="text-3xl font-bold">8 <span className="text-lg font-normal text-gray-500">Seasons</span></p>
        </div>

        <div className="card p-6 border-l-4 border-purple-500">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 bg-purple-100 rounded-lg text-purple-600">
              <FileText className="w-6 h-6"/>
            </div>
            <div>
              <h4 className="font-bold text-gray-700 dark:text-gray-300">AI Reports</h4>
              <p className="text-sm text-gray-500">Generated analyses</p>
            </div>
          </div>
          <p className="text-3xl font-bold">24 <span className="text-lg font-normal text-gray-500">Reports</span></p>
        </div>
      </div>

      <div className="card p-6">
        <div className="flex justify-between items-center mb-6">
          <h4 className="font-bold">Crop Yield History (Tons/Year)</h4>
          <div className="relative">
            <select 
              className="appearance-none bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg pl-4 pr-10 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-agri-green"
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
            >
              <option>Last 4 Years</option>
              <option>Last 10 Years</option>
              <option>All Time</option>
            </select>
            <ChevronDown className="w-4 h-4 absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 pointer-events-none"/>
          </div>
        </div>
        
        <div className="h-80 w-full">
          <ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}>
            <LineChart data={yieldHistoryData}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
              <XAxis dataKey="year" axisLine={false} tickLine={false} />
              <YAxis axisLine={false} tickLine={false} />
              <Tooltip contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
              <Legend />
              <Line type="monotone" dataKey="Tomato" stroke="#ef4444" strokeWidth={3} dot={{ r: 4 }} />
              <Line type="monotone" dataKey="Cotton" stroke="#10b981" strokeWidth={3} dot={{ r: 4 }} />
              <Line type="monotone" dataKey="Groundnut" stroke="#f59e0b" strokeWidth={3} dot={{ r: 4 }} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="card p-0 overflow-hidden">
        <div className="p-6 border-b border-gray-100 dark:border-gray-800 flex justify-between items-center">
          <h4 className="font-bold">Recent AI Analysis Reports</h4>
          <button onClick={() => alert("Loading complete report history...")} className="text-sm text-agri-green hover:underline">View All</button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-50 dark:bg-gray-800 text-gray-500 text-sm">
                <th className="p-4 font-medium">Date</th>
                <th className="p-4 font-medium">Report Type</th>
                <th className="p-4 font-medium">Crop Context</th>
                <th className="p-4 font-medium">Risk Level</th>
                <th className="p-4 font-medium text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-800 text-sm">
              {(() => {
                const existingReports = [
                  { date: 'Oct 15, 2025', type: 'Suitability Analysis', crop: 'Cotton', risk: 'Low', riskColor: 'text-green-600 bg-green-100' },
                  { date: 'Sep 02, 2025', type: 'Pest Prediction', crop: 'Tomato', risk: 'High', riskColor: 'text-red-600 bg-red-100' },
                  { date: 'Jun 20, 2025', type: 'Soil Health Scan', crop: 'All', risk: 'Moderate', riskColor: 'text-yellow-600 bg-yellow-100' },
                  { date: 'May 10, 2025', type: 'Irrigation Strategy', crop: 'Groundnut', risk: 'Low', riskColor: 'text-green-600 bg-green-100' }
                ];
                
                if (activeFarm?.aiReport) {
                  existingReports.unshift({
                    date: new Date(activeFarm.aiReport.date).toLocaleDateString(),
                    type: 'AI Crop Planning',
                    crop: activeFarm.aiReport.bestCrop.name,
                    risk: activeFarm.aiReport.bestCrop.riskLevel,
                    riskColor: activeFarm.aiReport.bestCrop.riskLevel === 'Low' ? 'text-green-600 bg-green-100' : 'text-yellow-600 bg-yellow-100'
                  });
                }
                
                return existingReports.map((row, i) => (
                  <tr key={i} className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors">
                    <td className="p-4 text-gray-600 dark:text-gray-300">{row.date}</td>
                    <td className="p-4 font-medium">{row.type}</td>
                    <td className="p-4 text-gray-600 dark:text-gray-300">{row.crop}</td>
                    <td className="p-4">
                      <span className={`px-2 py-1 rounded text-xs font-bold ${row.riskColor}`}>
                        {row.risk}
                      </span>
                    </td>
                    <td className="p-4 text-right">
                      <button onClick={() => handleDownloadPDF(row)} className="text-agri-green hover:text-agri-green-dark inline-flex items-center gap-1">
                        <Download className="w-4 h-4"/> PDF
                      </button>
                    </td>
                  </tr>
                ));
              })()}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ReportsHistoryTab;
